name: '01: Basic workflow'
on: workflow_dispatch
jobs:
  show-powershell:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: 'Show PowerShell info'
    runs-on: ubuntu-latest
    steps:
      - run: $PSVersionTable.PSVersion.ToString()
        shell: pwsh