name: '01: Basic workflow'
on: workflow_dispatch
jobs:
  show-powershell:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: 'Show PowerShell info'
    runs-on: ubuntu-latest
    steps:
      - run: $PSVersionTable.PSVersion.ToString()
        name: 'Print the current version'
        shell: pwsh
      - run: $PSVersionTable.PSVersion.ToString()
        if: ${{ matrix.os }} == 'windows-latest'
        name: 'Print the current version'
        shell: powershell