name: '01: Basic workflow'
on: workflow_dispatch
jobs:
  show-powershell:
    name: 'Show PowerShell info'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Print the current version'
        run: $PSVersionTable.PSVersion.ToString()
        shell: pwsh
      - name: 'Print the current version'
        run: $PSVersionTable.PSVersion.ToString()
        if: ${{ matrix.os }} == 'windows-latest'
        shell: powershell